export const GameplayConfig = {
	INITIAL_SNAKE_LENGTH: 3,
	MIN_SNAKE_LENGTH: 3,
	TARGET_FOOD_COUNT: 5,
	MAX_INPUT_QUEUE: 3,
	MAX_DELTA_MS: 200,
	POINTS_PER_FOOD: 10,
	POINTS_PER_SEQUENCE: 100,
	POINTS_EXIT_OPENED: 50,
	POINTS_LEVEL_ENTERED: 100,
	PENALTY_SEQUENCE_FAILED: 25
} as const;

export type GameplayConfigType = typeof GameplayConfig;
