export const GameplayConfig = {
	INITIAL_SNAKE_LENGTH: 3,
	MIN_SNAKE_LENGTH: 3,
	TARGET_FOOD_COUNT: 5,
	MAX_INPUT_QUEUE: 3,
	MAX_DELTA_MS: 200,
	POINTS_PER_FOOD: 10,
	POINTS_PER_SEQUENCE: 100,
	POINTS_EXIT_OPENED: 50,
	POINTS_LEVEL_ENTERED: 100,
	PENALTY_SEQUENCE_FAILED: 25,
	// Финал (Фаза 2)
	FINAL_TARGET_LENGTH: 8,
	FINAL_MOVES_PER_SEQUENCE: 14,
	POINTS_FINAL_SEQUENCE: 1000
} as const;
export type GameplayConfigType = typeof GameplayConfig;